esp1_rfid_motion/esp1_rfid_motion.ino File Reference
RFID + PIN based access controller with LCD, motion sensing, and MQTT.
Enumerations
enum class AccessResult : uint8_t { Denied
, Granted
, Denied
, Granted
 }
Access result enumeration.
Functions
MFRC522 mfrc522 (RFID_SS_PIN, RFID_RST_PIN)
MFRC522 RFID reader instance.
LiquidCrystal_I2C lcd (LCD_ADDRESS, LCD_COLUMNS, LCD_ROWS)
I2C LCD instance.
void lcdPrintLine (const __FlashStringHelper *msg, uint8_t line)
Clears an LCD line and prints a flash-resident string.
void lcdPrintLine (const char *msg, uint8_t line)
Clears an LCD line and prints a RAM-resident string.
static void forceLock ()
Forces the system back into locked idle state.
void makeEnteredPins (uint8_t pinLength)
Builds a masked PIN string for LCD display.
void callback (char *topic, byte *payload, unsigned int length)
MQTT message callback handler.
bool isDisplayActive (uint32_t now)
Checks whether the LCD backlight should remain active.
void onMotionDetected (uint32_t now)
Handles motion-detected events.
void onMotionIdle (uint32_t now)
Handles motion-idle state.
void updateMotionState (uint32_t now)
Updates motion state based on PIR sensor input.
void uidToHexString (const MFRC522::Uid &uid, char *output, size_t outputSize)
Converts an RFID UID to a hexadecimal string.
void handleRFID ()
Handles RFID card detection and request publishing.
void setup ()
Arduino setup function.
void loop ()
Arduino main loop.
Variables
WifiMqttClient net
WiFi + MQTT client wrapper.
constexpr char WIFI_SSID [] = "Mathias2.4"
WiFi SSID.
constexpr char WIFI_PASS [] = "mrbombasticcallmefantastic"
WiFi password.
constexpr char MQTT_HOST [] = "maqiatto.com"
MQTT broker hostname.
constexpr uint16_t MQTT_PORT = 1883
MQTT broker port.
constexpr char MQTT_USER [] = "hectorfoss@gmail.com"
MQTT username.
constexpr char MQTT_PASS [] = "potter"
MQTT password.
constexpr char DEVICE_ID [] = "door1"
Unique device identifier used in MQTT topics.
constexpr uint8_t RFID_SS_PIN = 15
RC522 SPI Slave Select pin (D8 / GPIO15).
constexpr uint8_t RFID_RST_PIN = 16
RC522 Reset pin (D0 / GPIO16).
constexpr uint8_t MOTION_PIN = 0
Motion sensor pin (D3 / GPIO0).
constexpr uint8_t I2C_SDA_PIN = 4
I2C SDA pin for LCD (D2 / GPIO4).
constexpr uint8_t I2C_SCL_PIN = 5
I2C SCL pin for LCD (D1 / GPIO5).
constexpr uint8_t LCD_COLUMNS = 16
Number of LCD columns.
constexpr uint8_t LCD_ROWS = 2
Number of LCD rows.
constexpr uint8_t LCD_ADDRESS = 0x27
I2C address of the LCD module.
constexpr uint32_t DISPLAY_MS = 3000
Duration (ms) to display text before resetting.
constexpr uint32_t DISPLAY_BACKLIGHT_MS = 5000
Duration (ms) to keep LCD backlight on after motion.
constexpr uint32_t PIN_TIME_MS = 15000
Time window (ms) for entering PIN after RFID success.
constexpr uint32_t UNLOCK_TIME_MS = 5000
Door unlock display duration (ms).
constexpr uint32_t POLL_MS = 30
Main loop polling delay (ms).
AccessResult rfidAccess
Result of RFID authentication.
AccessResult accessGranted
Result of PIN verification.
bool textshown = false
Indicates whether a status message is currently displayed.
uint32_t showTextUntil = 0
Timestamp (ms) when the displayed text should expire.
uint32_t showDisplayUntil = 0
Timestamp (ms) when LCD backlight should turn off.
bool motionActive = false
Indicates whether motion is currently considered active.
static char enteredPins [5] = " "
Masked PIN buffer shown on LCD (max 4 digits + null terminator).
Detailed Description
RFID + PIN based access controller with LCD, motion sensing, and MQTT.
Definition in file esp1_rfid_motion.ino.
Enumeration Type Documentation
AccessResult
enum class AccessResult : uint8_t [strong]
Access result enumeration.
Enumerator
Denied Access denied.
Granted Access granted.
Denied Access denied.
Granted Access granted.
Definition at line 140 of file esp1_rfid_motion.ino.
                        : uint8_t {
  Denied,
  Granted
};
Function Documentation
callback()
void callback (char * topic, byte * payload, unsigned int length)
MQTT message callback handler.
Parses incoming JSON messages and dispatches logic based on topic:
RFID access decision
Keypad PIN validation result
Keypad keypress feedback
Parameters
topic MQTT topic string.
payload Raw payload bytes.
length Payload length.
Definition at line 250 of file esp1_rfid_motion.ino.
                                                               {
  // Ignore empty MQTT messages
  if (length == 0) return;
  StaticJsonDocument<512> doc;
  // Deserialize JSON payload into document
  DeserializationError err = deserializeJson(doc, payload, length);
  // Abort if JSON parsing fails
  if (err) {
    Serial.print("JSON parse failed: ");
    Serial.println(err.c_str());
    return;
  }
  // ---------------------------------------------------------------------------
  // RFID access response
  // ---------------------------------------------------------------------------
  if (strcmp(topic, net.makeTopic("access/response").c_str()) == 0) {
    // Timestamp when request was sent (provided by backend)
    uint32_t requestMs = doc["sent_ts_ms"] | 0;
    // Compute round-trip delay to detect stale responses
    uint32_t deltaMs = millis() - requestMs;
    Serial.printf(
      "Request/Response time diff: %lu ms\n",
      deltaMs
    );
    // Ignore responses that took too long to arrive
    if (deltaMs > DISPLAY_MS) {
      Serial.println("Took too long to respond");
      return;
    }
    // Extract access decision from JSON payload
    rfidAccess = (doc["response"]["hasAccess"] | false)
      ? AccessResult::Granted
      : AccessResult::Denied;
    Serial.println("UID match: waiting for PIN...");
    // Handle denied RFID access immediately
    if (rfidAccess != AccessResult::Granted) {
      lcdPrintLine(F("Access Denied"), 0);
      textshown = true;
      showTextUntil = millis() + DISPLAY_MS;
      return;
    }
    // Prompt user to enter PIN after successful RFID
    lcdPrintLine(F("Enter PIN:"), 0);
    textshown = true;
    showTextUntil = millis() + PIN_TIME_MS;
    
  }
  // ---------------------------------------------------------------------------
  // Keypad PIN verification response
  // ---------------------------------------------------------------------------
  else if (strcmp(topic, net.makeTopic("access/keypad_response").c_str()) == 0) {
    // Ignore PIN responses if RFID was not authorized
    if (rfidAccess != AccessResult::Granted) return;
    // Extract PIN validation result
    accessGranted = (doc["response"]["accessGranted"] | false)
      ? AccessResult::Granted
      : AccessResult::Denied;
    // Handle incorrect PIN
    if (accessGranted != AccessResult::Granted) {
      Serial.println("Access Denied");
      lcdPrintLine(F("Access Denied"), 0);
      textshown = true;
      showTextUntil = millis() + DISPLAY_MS;
      return;
    }
    // Handle successful authentication
    Serial.println("Access Granted");
    lcdPrintLine(F("Access Granted"), 0);
    textshown = true;
    showTextUntil = millis() + UNLOCK_TIME_MS;
  }
  // ---------------------------------------------------------------------------
  // Keypad visual feedback (keypress)
  // ---------------------------------------------------------------------------
  else if (strcmp(topic, net.makeTopic("keypad/beep").c_str()) == 0) {
    // Only show keypad feedback after successful RFID
    if (rfidAccess != AccessResult::Granted) return;
    // Number of digits entered so far
    uint8_t pinLength = doc["data"]["pinlength"] | 0;
    // Update masked PIN display
    makeEnteredPins(pinLength);
    lcdPrintLine(enteredPins, 1);
  }
}
References accessGranted, Denied, DISPLAY_MS, enteredPins, Granted, lcdPrintLine(), makeEnteredPins(), net, PIN_TIME_MS, rfidAccess, showTextUntil, textshown, and UNLOCK_TIME_MS.
Referenced by setup().
forceLock()
void forceLock () [static]
Forces the system back into locked idle state.
Resets access state, clears temporary flags, and restores the default idle LCD message.
Definition at line 206 of file esp1_rfid_motion.ino.
                        {
  textshown = false; // Exit message display mode
  rfidAccess = AccessResult::Denied; // Clear RFID authorization state
  accessGranted = AccessResult::Denied; // Clear PIN authorization state
  lcdPrintLine(F("Scan RFID card"), 0); // Restore idle prompt
}
References accessGranted, Denied, lcdPrintLine(), rfidAccess, and textshown.
Referenced by loop().
handleRFID()
void handleRFID ()
Handles RFID card detection and request publishing.
Detects new cards, reads UID, updates LCD, and sends an MQTT access request.
Definition at line 450 of file esp1_rfid_motion.ino.
                  {
  // Exit if no new card is present
  if (!mfrc522.PICC_IsNewCardPresent()) {
    return;
  }
  // Exit if card UID could not be read
  if (!mfrc522.PICC_ReadCardSerial()) {
    return;
  }
  char uidString[21];
  uidToHexString(mfrc522.uid, uidString, sizeof(uidString));
  Serial.println(uidString);
  lcdPrintLine(F("Connecting..."), 0);
  textshown = true;
  showTextUntil = millis() + DISPLAY_MS;
  // Build JSON payload for access request
  StaticJsonDocument<64> data;
  data["uid"] = uidString;
  data["event"] = "RFID_Try";
  // Publish access request via MQTT
  bool ok = net.publishJson("access/request", data);
  Serial.println(ok ? "MQTT publish OK" : "MQTT publish FAILED");
  // Properly halt card communication
  mfrc522.PICC_HaltA();
  mfrc522.PCD_StopCrypto1();
}
References DISPLAY_MS, lcdPrintLine(), mfrc522(), net, showTextUntil, textshown, and uidToHexString().
Referenced by loop().
isDisplayActive()
bool isDisplayActive (uint32_t now)
Checks whether the LCD backlight should remain active.
Uses signed time comparison to safely handle millis() wraparound.
Parameters
now Current time in milliseconds.
Returns
true if display is active, false otherwise.
Definition at line 363 of file esp1_rfid_motion.ino.
                                   {
  return (int32_t)(now - showDisplayUntil) < 0;
}
References showDisplayUntil.
Referenced by loop(), and onMotionIdle().
lcd()
LiquidCrystal_I2C lcd (LCD_ADDRESS , LCD_COLUMNS , LCD_ROWS)
I2C LCD instance.
References LCD_ADDRESS, LCD_COLUMNS, and LCD_ROWS.
Referenced by lcdPrintLine(), lcdPrintLine(), onMotionDetected(), onMotionIdle(), and setup().
lcdPrintLine() [1/2]
void lcdPrintLine (const __FlashStringHelper * msg, uint8_t line)
Clears an LCD line and prints a flash-resident string.
Parameters
msg Flash string (use F("...")).
line LCD row index.
Definition at line 180 of file esp1_rfid_motion.ino.
                                                                {
  lcd.setCursor(0, line);
  lcd.print(" "); // Overwrite entire row to remove old content
  lcd.setCursor(0, line);
  lcd.print(msg);
}
References lcd().
Referenced by callback(), forceLock(), handleRFID(), and setup().
lcdPrintLine() [2/2]
void lcdPrintLine (const char * msg, uint8_t line)
Clears an LCD line and prints a RAM-resident string.
Parameters
msg C-string to print.
line LCD row index.
Definition at line 193 of file esp1_rfid_motion.ino.
                                                 {
  lcd.setCursor(0, line);
  lcd.print(" "); // Clear row to avoid leftover characters
  lcd.setCursor(0, line);
  lcd.print(msg);
}
References lcd().
loop()
void loop ()
Arduino main loop.
Executes non-blocking system logic:
MQTT client processing
Display timeout handling
Motion-based backlight control
RFID polling when active
Definition at line 546 of file esp1_rfid_motion.ino.
            {
  net.loop(); // Process MQTT traffic
  yield(); // Allow background WiFi tasks
  
  const uint32_t now = millis();
  // If a message is currently displayed, wait for timeout
  if (textshown) {
    if ((int32_t)(now - showTextUntil) >= 0) {
      forceLock(); // Reset system when timeout expires
    }
    delay(POLL_MS);
    return;
  }
  // Update LCD backlight based on motion sensor
  updateMotionState(now);
  // Only allow RFID scans when display is active
  if (isDisplayActive(now)) {
    handleRFID();
  }
}
References forceLock(), handleRFID(), isDisplayActive(), net, POLL_MS, showTextUntil, textshown, and updateMotionState().
makeEnteredPins()
void makeEnteredPins (uint8_t pinLength)
Builds a masked PIN string for LCD display.
Converts a numeric PIN length into a visual representation using '*' characters and trailing spaces.
Parameters
pinLength Number of digits entered so far.
Definition at line 221 of file esp1_rfid_motion.ino.
{
    // Clamp PIN length to display capacity (4 digits)
    if (pinLength > 4) {
        pinLength = 4;
    }
    // Fill entered portion with masking characters
    memset(enteredPins, '*', pinLength);
    // Fill remaining positions with spaces to clear old characters
    memset(enteredPins + pinLength, ' ', 4 - pinLength);
    // Ensure string is null-terminated
    enteredPins[4] = '\0';
}
References enteredPins.
Referenced by callback().
mfrc522()
MFRC522 mfrc522 (RFID_SS_PIN , RFID_RST_PIN)
MFRC522 RFID reader instance.
References RFID_RST_PIN, and RFID_SS_PIN.
Referenced by handleRFID(), and setup().
onMotionDetected()
void onMotionDetected (uint32_t now)
Handles motion-detected events.
Activates LCD backlight and refreshes display timeout.
Parameters
now Current time in milliseconds.
Definition at line 374 of file esp1_rfid_motion.ino.
                                    {
  if (!motionActive) {
    motionActive = true; // Mark motion as active
    Serial.println(F("Motion detected"));
    lcd.backlight(); // Turn on LCD backlight
  }
  // Extend backlight timeout while motion persists
  showDisplayUntil = now + DISPLAY_BACKLIGHT_MS;
}
References DISPLAY_BACKLIGHT_MS, lcd(), motionActive, and showDisplayUntil.
Referenced by updateMotionState().
onMotionIdle()
void onMotionIdle (uint32_t now)
Handles motion-idle state.
Turns off LCD backlight when motion has ceased and the timeout has expired.
Parameters
now Current time in milliseconds.
Definition at line 393 of file esp1_rfid_motion.ino.
                                {
  if (motionActive && !isDisplayActive(now)) {
    motionActive = false; // Mark motion as inactive
    lcd.noBacklight(); // Turn off LCD backlight
  }
}
References isDisplayActive(), lcd(), and motionActive.
Referenced by updateMotionState().
setup()
void setup ()
Arduino setup function.
Initializes hardware peripherals, LCD, WiFi, MQTT client, and topic subscriptions.
Definition at line 491 of file esp1_rfid_motion.ino.
             {
  delay(100); // Allow hardware to stabilize
  Serial.begin(115200);
  rfidAccess = AccessResult::Denied;
  Wire.begin(I2C_SDA_PIN, I2C_SCL_PIN);
  lcd.init();
  lcd.noBacklight();
  lcd.clear();
  lcdPrintLine(F("Scan RFID card"), 0);
  SPI.begin();
  mfrc522.PCD_Init();
  Serial.println("RC522 initialized");
  pinMode(MOTION_PIN, INPUT);
  net.begin(
    WIFI_SSID,
    WIFI_PASS,
    MQTT_HOST,
    MQTT_PORT,
    MQTT_USER,
    MQTT_PASS,
    DEVICE_ID,
    "site1"
  );
  Serial.println("MQTT ready");
  net.setCallback(callback);
  // Subscribe to required MQTT topics
  Serial.printf("access/response MQTT subscribe %s\n",
    net.subscribe(net.makeTopic("access/response").c_str()) ? "OK" : "FAILED");
  Serial.printf("access/keypad_response MQTT subscribe %s\n",
    net.subscribe(net.makeTopic("access/keypad_response").c_str()) ? "OK" : "FAILED");
  
  Serial.printf("keypad/beep MQTT subscribe %s\n",
    net.subscribe(net.makeTopic("keypad/beep").c_str()) ? "OK" : "FAILED");
}
References callback(), Denied, DEVICE_ID, I2C_SCL_PIN, I2C_SDA_PIN, lcd(), lcdPrintLine(), mfrc522(), MOTION_PIN, MQTT_HOST, MQTT_PASS, MQTT_PORT, MQTT_USER, net, rfidAccess, WIFI_PASS, and WIFI_SSID.
uidToHexString()
void uidToHexString (const MFRC522::Uid & uid, char * output, size_t outputSize)
Converts an RFID UID to a hexadecimal string.
Each UID byte is encoded as two uppercase hexadecimal characters.
Parameters
uid MFRC522 UID structure.
output Destination buffer.
outputSize Size of destination buffer.
Definition at line 426 of file esp1_rfid_motion.ino.
                                                                            {
  // Ensure output buffer is large enough:
  // 2 hex characters per byte + null terminator
  if (outputSize < (uid.size * 2 + 1)) {
    output[0] = '\0'; // Fail safely with empty string
    return;
  }
  // Convert each UID byte into two hex characters
  for (byte i = 0; i < uid.size; i++) {
    sprintf(&output[i * 2], "%02X", uid.uidByte[i]);
  }
  // Explicitly terminate C-string
  output[uid.size * 2] = '\0';
}
Referenced by handleRFID().
updateMotionState()
void updateMotionState (uint32_t now)
Updates motion state based on PIR sensor input.
Dispatches to motion-detected or motion-idle handlers.
Parameters
now Current time in milliseconds.
Definition at line 407 of file esp1_rfid_motion.ino.
                                     {
  const bool motion = digitalRead(MOTION_PIN); // Read PIR sensor state
  if (motion) {
    onMotionDetected(now);
  } else {
    onMotionIdle(now);
  }
}
References MOTION_PIN, onMotionDetected(), and onMotionIdle().
Referenced by loop().
Variable Documentation
accessGranted
AccessResult accessGranted
Result of PIN verification.
Definition at line 149 of file esp1_rfid_motion.ino.
Referenced by callback(), forceLock(), and forceLock().
DEVICE_ID
char DEVICE_ID[] = "door1" [constexpr]
Unique device identifier used in MQTT topics.
Definition at line 70 of file esp1_rfid_motion.ino.
Referenced by setup().
DISPLAY_BACKLIGHT_MS
uint32_t DISPLAY_BACKLIGHT_MS = 5000 [constexpr]
Duration (ms) to keep LCD backlight on after motion.
Definition at line 112 of file esp1_rfid_motion.ino.
Referenced by onMotionDetected().
DISPLAY_MS
uint32_t DISPLAY_MS = 3000 [constexpr]
Duration (ms) to display text before resetting.
Definition at line 109 of file esp1_rfid_motion.ino.
Referenced by callback(), and handleRFID().
enteredPins
char enteredPins[5] = " " [static]
Masked PIN buffer shown on LCD (max 4 digits + null terminator).
Filled with '*' for entered digits and spaces for remaining slots.
Definition at line 168 of file esp1_rfid_motion.ino.
Referenced by callback(), and makeEnteredPins().
I2C_SCL_PIN
uint8_t I2C_SCL_PIN = 5 [constexpr]
I2C SCL pin for LCD (D1 / GPIO5).
Definition at line 89 of file esp1_rfid_motion.ino.
Referenced by setup().
I2C_SDA_PIN
uint8_t I2C_SDA_PIN = 4 [constexpr]
I2C SDA pin for LCD (D2 / GPIO4).
Definition at line 86 of file esp1_rfid_motion.ino.
Referenced by setup().
LCD_ADDRESS
uint8_t LCD_ADDRESS = 0x27 [constexpr]
I2C address of the LCD module.
Definition at line 102 of file esp1_rfid_motion.ino.
Referenced by lcd().
LCD_COLUMNS
uint8_t LCD_COLUMNS = 16 [constexpr]
Number of LCD columns.
Definition at line 96 of file esp1_rfid_motion.ino.
Referenced by lcd().
LCD_ROWS
uint8_t LCD_ROWS = 2 [constexpr]
Number of LCD rows.
Definition at line 99 of file esp1_rfid_motion.ino.
Referenced by lcd().
MOTION_PIN
uint8_t MOTION_PIN = 0 [constexpr]
Motion sensor pin (D3 / GPIO0).
Definition at line 83 of file esp1_rfid_motion.ino.
Referenced by setup(), and updateMotionState().
motionActive
bool motionActive = false
Indicates whether motion is currently considered active.
Definition at line 161 of file esp1_rfid_motion.ino.
Referenced by onMotionDetected(), and onMotionIdle().
MQTT_HOST
char MQTT_HOST[] = "maqiatto.com" [constexpr]
MQTT broker hostname.
Definition at line 61 of file esp1_rfid_motion.ino.
Referenced by setup().
MQTT_PASS
char MQTT_PASS[] = "potter" [constexpr]
MQTT password.
Definition at line 67 of file esp1_rfid_motion.ino.
Referenced by setup().
MQTT_PORT
uint16_t MQTT_PORT = 1883 [constexpr]
MQTT broker port.
Definition at line 63 of file esp1_rfid_motion.ino.
Referenced by setup().
MQTT_USER
char MQTT_USER[] = "hectorfoss@gmail.com" [constexpr]
MQTT username.
Definition at line 65 of file esp1_rfid_motion.ino.
Referenced by setup().
net
WifiMqttClient net
WiFi + MQTT client wrapper.
Definition at line 53 of file esp1_rfid_motion.ino.
Referenced by callback(), handleRFID(), loop(), publishTap(), and setup().
PIN_TIME_MS
uint32_t PIN_TIME_MS = 15000 [constexpr]
Time window (ms) for entering PIN after RFID success.
Definition at line 115 of file esp1_rfid_motion.ino.
Referenced by callback().
POLL_MS
uint32_t POLL_MS = 30 [constexpr]
Main loop polling delay (ms).
Definition at line 121 of file esp1_rfid_motion.ino.
Referenced by loop().
RFID_RST_PIN
uint8_t RFID_RST_PIN = 16 [constexpr]
RC522 Reset pin (D0 / GPIO16).
Definition at line 80 of file esp1_rfid_motion.ino.
Referenced by mfrc522().
RFID_SS_PIN
uint8_t RFID_SS_PIN = 15 [constexpr]
RC522 SPI Slave Select pin (D8 / GPIO15).
Definition at line 77 of file esp1_rfid_motion.ino.
Referenced by mfrc522().
rfidAccess
AccessResult rfidAccess
Result of RFID authentication.
Definition at line 146 of file esp1_rfid_motion.ino.
Referenced by callback(), forceLock(), and setup().
showDisplayUntil
uint32_t showDisplayUntil = 0
Timestamp (ms) when LCD backlight should turn off.
Definition at line 158 of file esp1_rfid_motion.ino.
Referenced by isDisplayActive(), and onMotionDetected().
showTextUntil
uint32_t showTextUntil = 0
Timestamp (ms) when the displayed text should expire.
Definition at line 155 of file esp1_rfid_motion.ino.
Referenced by callback(), handleRFID(), and loop().
textshown
bool textshown = false
Indicates whether a status message is currently displayed.
Definition at line 152 of file esp1_rfid_motion.ino.
Referenced by callback(), forceLock(), handleRFID(), and loop().
UNLOCK_TIME_MS
uint32_t UNLOCK_TIME_MS = 5000 [constexpr]
Door unlock display duration (ms).
Definition at line 118 of file esp1_rfid_motion.ino.
Referenced by callback().
WIFI_PASS
char WIFI_PASS[] = "mrbombasticcallmefantastic" [constexpr]
WiFi password.
Definition at line 58 of file esp1_rfid_motion.ino.
Referenced by setup().
WIFI_SSID
char WIFI_SSID[] = "Mathias2.4" [constexpr]
WiFi SSID.
Definition at line 56 of file esp1_rfid_motion.ino.
Referenced by setup().