esp2_keypad/esp2_keypad.ino File Reference
Keypad-based PIN entry controller with MQTT backend integration.
Functions
void callback (char *topic, byte *payload, unsigned int length)
MQTT message callback handler.
void setup ()
Arduino setup function.
void reset_code ()
Resets the PIN input buffer and index.
void publishTap ()
Publishes keypad tap feedback via MQTT.
void loop ()
Arduino main loop.
Variables
WifiMqttClient net
WiFi + MQTT client wrapper.
constexpr char WIFI_SSID [] = "Mathias2.4"
WiFi SSID.
constexpr char WIFI_PASS [] = "mrbombasticcallmefantastic"
WiFi password.
constexpr char MQTT_HOST [] = "maqiatto.com"
MQTT broker hostname.
constexpr uint16_t MQTT_PORT = 1883
MQTT broker port.
constexpr char MQTT_USER [] = "hectorfoss@gmail.com"
MQTT username.
constexpr char MQTT_PASS [] = "potter"
MQTT password.
constexpr char DEVICE_ID [] = "door1"
Unique device identifier used in MQTT topics.
const byte ROWS = 4
Number of rows in the keypad matrix.
const byte COLS = 4
Number of columns in the keypad matrix.
char keys [ROWS][COLS]
Logical keypad layout.
byte rowPins [ROWS] = {16, 5, 4, 0}
GPIO pins connected to keypad rows.
byte colPins [COLS] = {2, 14, 12, 13}
GPIO pins connected to keypad columns.
Keypad keypad = Keypad(makeKeymap(keys), rowPins, colPins, ROWS, COLS)
Keypad instance handling scanning and debouncing.
constexpr uint8_t CODE_LENGTH = 4
Required PIN length.
char input [CODE_LENGTH+1] = {0}
Input buffer for PIN digits.
uint8_t currentIdx = 0
Current index into the PIN buffer.
bool kpEnabled = false
Indicates whether keypad input is currently enabled.
Detailed Description
Keypad-based PIN entry controller with MQTT backend integration.
Definition in file esp2_keypad.ino.
Function Documentation
callback()
void callback (char * topic, byte * payload, unsigned int length)
MQTT message callback handler.
Handles:
Enabling keypad input after RFID access is granted
Disabling keypad input after PIN validation completes
Parameters
topic MQTT topic string.
payload Raw payload bytes.
length Payload length.
Definition at line 150 of file esp2_keypad.ino.
                                                               {
  // Ignore empty MQTT messages
  if (length == 0) return;
  StaticJsonDocument<512> doc;
  // Parse JSON payload
  DeserializationError err = deserializeJson(doc, payload, length);
  // Abort on JSON parsing failure
  if (err) {
    Serial.print("JSON parse failed: ");
    Serial.println(err.c_str());
    return;
  }
  // ---------------------------------------------------------------------------
  // RFID access response: enable or disable keypad
  // ---------------------------------------------------------------------------
  if (strcmp(topic, net.makeTopic("access/response").c_str()) == 0) {
    // Enable keypad only if RFID access was granted
    kpEnabled = (doc["response"]["hasAccess"] | false)
      ? true
      : false;
  }
  // ---------------------------------------------------------------------------
  // PIN verification response: always disable keypad afterward
  // ---------------------------------------------------------------------------
  else if (strcmp(topic, net.makeTopic("access/keypad_response").c_str()) == 0) {
    // Prevent further input until next RFID authorization
    kpEnabled = false;
  }
}
References kpEnabled, and net.
loop()
void loop ()
Arduino main loop.
Handles:
MQTT client processing
Keypad scanning
PIN entry logic
PIN submission and reset
Definition at line 265 of file esp2_keypad.ino.
            {
  net.loop(); // Process MQTT traffic
  yield(); // Allow background WiFi tasks
  // Read keypad state (non-blocking)
  char key = keypad.getKey();
  // Ignore input if no key pressed or keypad is disabled
  if (key == NO_KEY || !kpEnabled) {
    return;
  }
  // ---------------------------------------------------------------------------
  // Numeric key input
  // ---------------------------------------------------------------------------
  if (key >= '0' && key <= '9') {
    // Only accept input if buffer is not full
    if (currentIdx < CODE_LENGTH) {
      input[currentIdx++] = key; // Store digit
      input[currentIdx] = '\0'; // Maintain null-terminated string
      Serial.print("Key: ");
      Serial.println(key);
    }
  }
  // ---------------------------------------------------------------------------
  // Submit PIN using '#'
  // ---------------------------------------------------------------------------
  else if (key == '#') {
    // Only submit if required PIN length is reached
    if (currentIdx == CODE_LENGTH) {
      Serial.print("Submitting code: ");
      Serial.println(input);
      // Build JSON payload for PIN submission
      StaticJsonDocument<64> data;
      data["event"] = "KP_try";
      data["code"] = input;
      net.publishJson("keypad/submit", data);
    }
    else {
      Serial.println("Code too short, resetting.");
    }
    // Always reset buffer after submission attempt
    reset_code();
  }
  // ---------------------------------------------------------------------------
  // Clear input using '*'
  // ---------------------------------------------------------------------------
  else if (key == '*') {
    reset_code();
    Serial.println("Input cleared");
  }
  // Ignore unsupported keys (A-D)
  else {
    return;
  }
  // Any valid keypress is treated as a tap event
  publishTap();
}
References CODE_LENGTH, currentIdx, input, keypad, kpEnabled, net, publishTap(), and reset_code().
publishTap()
void publishTap ()
Publishes keypad tap feedback via MQTT.
Sends the current PIN length after each valid keypress, allowing external systems to provide visual or audio feedback.
Definition at line 244 of file esp2_keypad.ino.
                  {
  StaticJsonDocument<64> data;
  data["event"] = "KP_tap";
  data["pinlength"] = currentIdx;
  net.publishJson("keypad/tap", data);
}
References currentIdx, and net.
Referenced by loop().
reset_code()
void reset_code ()
Resets the PIN input buffer and index.
Clears any partially entered PIN and prepares the buffer for new input.
Definition at line 233 of file esp2_keypad.ino.
                  {
  memset(input, 0, sizeof(input)); // Clear buffer contents
  currentIdx = 0; // Reset write index
}
References currentIdx, and input.
Referenced by loop().
setup()
void setup ()
Arduino setup function.
Initializes Serial output, WiFi connection, MQTT client, and topic subscriptions.
Definition at line 197 of file esp2_keypad.ino.
             {
  Serial.begin(115200);
  net.begin(
    WIFI_SSID,
    WIFI_PASS,
    MQTT_HOST,
    MQTT_PORT,
    MQTT_USER,
    MQTT_PASS,
    DEVICE_ID,
    "site1"
  );
  Serial.println("Keypad + MQTT ready");
  net.setCallback(callback);
  // Subscribe to access control topics
  Serial.printf("access/response MQTT subscribe %s\n",
    net.subscribe(net.makeTopic("access/response").c_str()) ? "OK" : "FAILED");
  Serial.printf("access/keypad_response MQTT subscribe %s\n",
    net.subscribe(net.makeTopic("access/keypad_response").c_str()) ? "OK" : "FAILED");
}
References callback(), DEVICE_ID, MQTT_HOST, MQTT_PASS, MQTT_PORT, MQTT_USER, net, WIFI_PASS, and WIFI_SSID.
Variable Documentation
CODE_LENGTH
uint8_t CODE_LENGTH = 4 [constexpr]
Required PIN length.
Definition at line 116 of file esp2_keypad.ino.
Referenced by loop().
colPins
byte colPins[COLS] = {2, 14, 12, 13}
GPIO pins connected to keypad columns.
Order must match COLS definition. D4, D5, D6, D7
Definition at line 96 of file esp2_keypad.ino.
{2, 14, 12, 13};
COLS
const byte COLS = 4
Number of columns in the keypad matrix.
Definition at line 69 of file esp2_keypad.ino.
currentIdx
uint8_t currentIdx = 0
Current index into the PIN buffer.
Definition at line 126 of file esp2_keypad.ino.
Referenced by loop(), publishTap(), and reset_code().
DEVICE_ID
char DEVICE_ID[] = "door1" [constexpr]
Unique device identifier used in MQTT topics.
Definition at line 61 of file esp2_keypad.ino.
input
char input[CODE_LENGTH+1] = {0}
Input buffer for PIN digits.
One extra byte is reserved for the null terminator.
Definition at line 123 of file esp2_keypad.ino.
{0};
Referenced by loop(), and reset_code().
keypad
Keypad keypad = Keypad(makeKeymap(keys), rowPins, colPins, ROWS, COLS)
Keypad instance handling scanning and debouncing.
Definition at line 111 of file esp2_keypad.ino.
Referenced by loop().
keys
char keys[ROWS][COLS]
Initial value:
          = {
  {'1','2','3','A'},
  {'4','5','6','B'},
  {'7','8','9','C'},
  {'*','0','#','D'}
}
Logical keypad layout.
Defines the character returned for each row/column intersection.
Definition at line 76 of file esp2_keypad.ino.
                      {
  {'1','2','3','A'},
  {'4','5','6','B'},
  {'7','8','9','C'},
  {'*','0','#','D'}
};
kpEnabled
bool kpEnabled = false
Indicates whether keypad input is currently enabled.
This flag is controlled via MQTT messages from the access controller.
Definition at line 133 of file esp2_keypad.ino.
Referenced by callback(), and loop().
MQTT_HOST
char MQTT_HOST[] = "maqiatto.com" [constexpr]
MQTT broker hostname.
Definition at line 52 of file esp2_keypad.ino.
MQTT_PASS
char MQTT_PASS[] = "potter" [constexpr]
MQTT password.
Definition at line 58 of file esp2_keypad.ino.
MQTT_PORT
uint16_t MQTT_PORT = 1883 [constexpr]
MQTT broker port.
Definition at line 54 of file esp2_keypad.ino.
MQTT_USER
char MQTT_USER[] = "hectorfoss@gmail.com" [constexpr]
MQTT username.
Definition at line 56 of file esp2_keypad.ino.
net
WifiMqttClient net
WiFi + MQTT client wrapper.
Definition at line 44 of file esp2_keypad.ino.
rowPins
byte rowPins[ROWS] = {16, 5, 4, 0}
GPIO pins connected to keypad rows.
Order must match ROWS definition. D0, D1, D2, D3
Definition at line 89 of file esp2_keypad.ino.
{16, 5, 4, 0};
ROWS
const byte ROWS = 4
Number of rows in the keypad matrix.
Definition at line 66 of file esp2_keypad.ino.
WIFI_PASS
char WIFI_PASS[] = "mrbombasticcallmefantastic" [constexpr]
WiFi password.
Definition at line 49 of file esp2_keypad.ino.
WIFI_SSID
char WIFI_SSID[] = "Mathias2.4" [constexpr]
WiFi SSID.
Definition at line 47 of file esp2_keypad.ino.