esp3/esp3.ino File Reference
Door actuator, buzzer, and LED controller with MQTT integration.
Classes
struct BuzzerPattern
Describes a buzzer sound pattern. More...
Macros
#define POT_PIN A0
Analog pin for potentiometer (admin servo control).
Enumerations
enum class AccessResult : uint8_t { Denied
, Granted
, Denied
, Granted
 }
Access result enumeration.
enum BuzzerState { BUZZER_IDLE
, BUZZER_ON
, BUZZER_OFF
 }
Buzzer state enumeration.
Functions
void playPattern (const unsigned int *timings, uint8_t length)
Starts playing a buzzer pattern.
void updateBuzzer ()
Advances the buzzer state machine.
void stopBuzzer ()
Immediately stops any active buzzer sound.
void playLockSound ()
Plays lock sound pattern.
void playUnlockSound ()
Plays unlock sound pattern.
void playDeniedSound ()
Plays denied-access sound pattern.
void playTapSound ()
Plays keypad tap sound.
static void forceLock ()
Forces the system into a locked idle state.
void callback (char *topic, byte *payload, unsigned int length)
MQTT message callback handler.
void setup ()
Arduino setup function.
void loop ()
Arduino main loop.
Variables
WifiMqttClient net
WiFi + MQTT client wrapper.
constexpr char WIFI_SSID [] = "Mathias2.4"
WiFi SSID.
constexpr char WIFI_PASS [] = "mrbombasticcallmefantastic"
WiFi password.
constexpr char MQTT_HOST [] = "maqiatto.com"
MQTT broker hostname.
constexpr uint16_t MQTT_PORT = 1883
MQTT broker port.
constexpr char MQTT_USER [] = "hectorfoss@gmail.com"
MQTT username.
constexpr char MQTT_PASS [] = "potter"
MQTT password.
constexpr char DEVICE_ID [] = "door1"
Unique device identifier used in MQTT topics.
constexpr uint8_t RED_PIN = 4
GPIO pin assignments.
constexpr uint8_t GREEN_PIN = 0
Green LED (unlocked).
constexpr uint8_t BUZZER_PIN = 14
Piezo buzzer.
constexpr uint8_t SERVO_PIN = 13
Servo signal pin.
constexpr uint32_t UNLOCK_TIME_MS = 5000
Door unlock duration (ms).
uint32_t unlockUntil = 0
Timestamp (ms) until which the door remains unlocked.
bool unlocked = false
Indicates whether the door is currently unlocked.
AccessResult accessGranted
Result of keypad PIN verification.
bool rfidAccess = false
Indicates whether RFID access was granted.
Servo lock_servo
Servo instance controlling the lock mechanism.
bool servoOpen = false
Indicates whether the servo is currently in the open position.
uint8_t servoAngle
Current servo angle (derived from potentiometer in admin mode).
bool adminServoControl = false
Enables direct servo control via potentiometer (admin mode).
const unsigned int deniedTimings []
Denied access: single long beep.
const unsigned int lockTimings []
Lock sound: long-long-long pattern.
const unsigned int unlockTimings []
Unlock sound: short-short pattern.
const unsigned int beepTimings []
Keypad tap sound: short beep.
BuzzerState buzzerState = BUZZER_IDLE
Current buzzer state.
BuzzerPattern currentPattern = {nullptr, 0}
Currently active buzzer pattern.
uint8_t stepIndex = 0
Index into the timing array.
unsigned long lastChange = 0
Timestamp of last buzzer state change.
Detailed Description
Door actuator, buzzer, and LED controller with MQTT integration.
Definition in file esp3.ino.
Class Documentation
struct BuzzerPattern
Describes a buzzer sound pattern.
Definition at line 170 of file esp3.ino.
Class Members
uint8_t
length
Number of timing entries.
const unsigned int *
timings
Pointer to timing array.
Macro Definition Documentation
POT_PIN
#define POT_PIN A0
Analog pin for potentiometer (admin servo control).
Definition at line 80 of file esp3.ino.
Referenced by loop().
Enumeration Type Documentation
AccessResult
enum class AccessResult : uint8_t [strong]
Access result enumeration.
Enumerator
Denied Access denied.
Granted Access granted.
Denied Access denied.
Granted Access granted.
Definition at line 102 of file esp3.ino.
                        : uint8_t {
  Denied,
  Granted
};
BuzzerState
enum BuzzerState
Buzzer state enumeration.
Enumerator
BUZZER_IDLE No sound playing.
BUZZER_ON Buzzer currently active.
BUZZER_OFF Silent gap between beeps.
Definition at line 161 of file esp3.ino.
                 {
  BUZZER_IDLE,
  BUZZER_ON,
  BUZZER_OFF
};
Function Documentation
callback()
void callback (char * topic, byte * payload, unsigned int length)
MQTT message callback handler.
Handles:
Keypad access responses (unlock / deny)
RFID access denials
Keypad tap beep feedback
Admin servo control enable/disable
Parameters
topic MQTT topic string.
payload Raw payload bytes.
length Payload length.
Definition at line 318 of file esp3.ino.
                                                               {
  // Ignore empty MQTT messages
  if (length == 0) return;
  StaticJsonDocument<512> doc;
  DeserializationError err = deserializeJson(doc, payload, length);
  // Abort if JSON parsing fails
  if (err) {
    Serial.print("JSON parse failed: ");
    Serial.println(err.c_str());
    return;
  }
  // ---------------------------------------------------------------------------
  // Keypad PIN verification response
  // ---------------------------------------------------------------------------
  if (strcmp(topic, net.makeTopic("access/keypad_response").c_str()) == 0) {
    // Ignore keypad responses during admin servo control
    if (adminServoControl) return;
    accessGranted = (doc["response"]["accessGranted"] | false)
      ? AccessResult::Granted
      : AccessResult::Denied;
    if (accessGranted != AccessResult::Granted) {
      Serial.println("Access Denied");
      playDeniedSound();
      forceLock();
      return;
    }
    // Access granted: unlock door
    Serial.println("Unlocking door");
    playUnlockSound();
    lock_servo.write(180); // Move servo to unlocked position
    servoOpen = true;
    digitalWrite(GREEN_PIN, HIGH);
    digitalWrite(RED_PIN, LOW);
    unlocked = true;
    unlockUntil = millis() + UNLOCK_TIME_MS;
  }
  // ---------------------------------------------------------------------------
  // RFID access response (only react to denial)
  // ---------------------------------------------------------------------------
  else if (strcmp(topic, net.makeTopic("access/response").c_str()) == 0) {
    rfidAccess = (doc["response"]["hasAccess"] | false)
      ? true
      : false;
    if (!rfidAccess) {
      Serial.println("Access Denied");
      playDeniedSound();
      forceLock();
      return;
    }
  }
  // ---------------------------------------------------------------------------
  // Keypad tap feedback
  // ---------------------------------------------------------------------------
  else if (strcmp(topic, net.makeTopic("keypad/beep").c_str()) == 0) {
    // Only beep if RFID access is valid
    if (!rfidAccess) return;
    playTapSound();
  }
  // ---------------------------------------------------------------------------
  // Admin servo control enable/disable
  // ---------------------------------------------------------------------------
  else if (strcmp(topic, net.makeTopic("admin/servo_control").c_str()) == 0) {
    adminServoControl = (doc["data"]["adminServoControl"] | false)
      ? true
      : false;
    if (!adminServoControl) {
      Serial.println("Admin servo control disabled");
      forceLock(); // Reset servo to locked state
      return;
    }
    Serial.println("Admin servo control enabled");
  }
}
References accessGranted, adminServoControl, Denied, forceLock(), Granted, GREEN_PIN, lock_servo, net, playDeniedSound(), playTapSound(), playUnlockSound(), RED_PIN, rfidAccess, servoOpen, UNLOCK_TIME_MS, unlocked, and unlockUntil.
forceLock()
void forceLock () [static]
Forces the system into a locked idle state.
Resets access state
Sets LEDs to "locked"
Moves servo to closed position if needed
Definition at line 288 of file esp3.ino.
                        {
  accessGranted = AccessResult::Denied;
  unlocked = false;
  digitalWrite(RED_PIN, HIGH);
  digitalWrite(GREEN_PIN, LOW);
  if (servoOpen) {
    lock_servo.write(0); // Move servo to locked position
    servoOpen = false;
  }
}
References accessGranted, Denied, GREEN_PIN, lock_servo, RED_PIN, servoOpen, and unlocked.
Referenced by callback(), and loop().
loop()
void loop ()
Arduino main loop.
Handles:
MQTT processing
Buzzer state machine updates
Servo admin override mode
Automatic relocking after timeout
Definition at line 484 of file esp3.ino.
            {
  net.loop();
  yield();
  // Advance buzzer state machine
  updateBuzzer();
  // ---------------------------------------------------------------------------
  // Admin servo control mode
  // ---------------------------------------------------------------------------
  if (adminServoControl) {
    // Map potentiometer value to servo angle
    servoAngle = (int)(analogRead(POT_PIN) / 1023.0f * 180.0f);
    servoAngle = constrain(servoAngle, 0, 180);
    lock_servo.write(servoAngle);
    return;
  }
  // ---------------------------------------------------------------------------
  // Automatic relock after unlock timeout
  // ---------------------------------------------------------------------------
  const uint32_t now = millis();
  if (unlocked && (int32_t)(now - unlockUntil) >= 0) {
    Serial.println("Locking door");
    playLockSound();
    forceLock();
  }
}
References adminServoControl, forceLock(), lock_servo, net, playLockSound(), POT_PIN, servoAngle, unlocked, unlockUntil, and updateBuzzer().
playDeniedSound()
void playDeniedSound ()
Plays denied-access sound pattern.
Definition at line 264 of file esp3.ino.
                       {
  stopBuzzer();
  playPattern(deniedTimings,
              sizeof(deniedTimings) / sizeof(deniedTimings[0]));
}
References deniedTimings, playPattern(), and stopBuzzer().
Referenced by callback().
playLockSound()
void playLockSound ()
Plays lock sound pattern.
Definition at line 250 of file esp3.ino.
                     {
  stopBuzzer();
  playPattern(lockTimings,
              sizeof(lockTimings) / sizeof(lockTimings[0]));
}
References lockTimings, playPattern(), and stopBuzzer().
Referenced by loop().
playPattern()
void playPattern (const unsigned int * timings, uint8_t length)
Starts playing a buzzer pattern.
Parameters
timings Pointer to timing array.
length Number of elements in the timing array.
Definition at line 193 of file esp3.ino.
                                                              {
  // Prevent overlapping sound patterns
  if (buzzerState != BUZZER_IDLE) return;
  currentPattern.timings = timings;
  currentPattern.length = length;
  stepIndex = 0;
  buzzerState = BUZZER_ON;
  lastChange = millis();
  digitalWrite(BUZZER_PIN, HIGH); // Start with buzzer ON
}
References BUZZER_IDLE, BUZZER_ON, BUZZER_PIN, buzzerState, currentPattern, lastChange, and stepIndex.
Referenced by playDeniedSound(), playLockSound(), playTapSound(), and playUnlockSound().
playTapSound()
void playTapSound ()
Plays keypad tap sound.
Definition at line 271 of file esp3.ino.
                    {
  stopBuzzer();
  playPattern(beepTimings,
              sizeof(beepTimings) / sizeof(beepTimings[0]));
}
References beepTimings, playPattern(), and stopBuzzer().
Referenced by callback().
playUnlockSound()
void playUnlockSound ()
Plays unlock sound pattern.
Definition at line 257 of file esp3.ino.
                       {
  stopBuzzer();
  playPattern(unlockTimings,
              sizeof(unlockTimings) / sizeof(unlockTimings[0]));
}
References playPattern(), stopBuzzer(), and unlockTimings.
Referenced by callback().
setup()
void setup ()
Arduino setup function.
Initializes GPIOs, servo, WiFi, MQTT client, and topic subscriptions.
Definition at line 423 of file esp3.ino.
             {
  pinMode(RED_PIN, OUTPUT);
  pinMode(GREEN_PIN, OUTPUT);
  pinMode(BUZZER_PIN, OUTPUT);
  lock_servo.attach(SERVO_PIN);
  // Initialize outputs to safe state
  digitalWrite(RED_PIN, LOW);
  digitalWrite(GREEN_PIN, LOW);
  digitalWrite(BUZZER_PIN, LOW);
  lock_servo.write(0); // Locked position
  servoAngle = 0;
  delay(100);
  Serial.begin(115200);
  net.begin(
    WIFI_SSID,
    WIFI_PASS,
    MQTT_HOST,
    MQTT_PORT,
    MQTT_USER,
    MQTT_PASS,
    DEVICE_ID,
    "site1"
  );
  Serial.println("WiFi & MQTT ready");
  net.setCallback(callback);
  // Subscribe to required MQTT topics
  Serial.printf("access/response MQTT subscribe %s\n",
    net.subscribe(net.makeTopic("access/response").c_str()) ? "OK" : "FAILED");
  Serial.printf("access/keypad_response MQTT subscribe %s\n",
    net.subscribe(net.makeTopic("access/keypad_response").c_str()) ? "OK" : "FAILED");
  Serial.printf("keypad/beep MQTT subscribe %s\n",
    net.subscribe(net.makeTopic("keypad/beep").c_str()) ? "OK" : "FAILED");
  Serial.printf("admin/servo_control MQTT subscribe %s\n",
    net.subscribe(net.makeTopic("admin/servo_control").c_str()) ? "OK" : "FAILED");
}
References BUZZER_PIN, callback(), DEVICE_ID, GREEN_PIN, lock_servo, MQTT_HOST, MQTT_PASS, MQTT_PORT, MQTT_USER, net, RED_PIN, SERVO_PIN, servoAngle, WIFI_PASS, and WIFI_SSID.
stopBuzzer()
void stopBuzzer ()
Immediately stops any active buzzer sound.
Definition at line 244 of file esp3.ino.
                  {
  buzzerState = BUZZER_IDLE;
  digitalWrite(BUZZER_PIN, LOW);
}
References BUZZER_IDLE, BUZZER_PIN, and buzzerState.
Referenced by playDeniedSound(), playLockSound(), playTapSound(), and playUnlockSound().
updateBuzzer()
void updateBuzzer ()
Advances the buzzer state machine.
Must be called frequently from the main loop.
Definition at line 213 of file esp3.ino.
                    {
  if (buzzerState == BUZZER_IDLE) return;
  unsigned long now = millis();
  // Wait until current timing interval expires
  if (now - lastChange < currentPattern.timings[stepIndex]) return;
  lastChange = now;
  stepIndex++;
  // End of pattern reached
  if (stepIndex >= currentPattern.length) {
    digitalWrite(BUZZER_PIN, LOW);
    buzzerState = BUZZER_IDLE;
    return;
  }
  // Toggle buzzer state
  if (buzzerState == BUZZER_ON) {
    digitalWrite(BUZZER_PIN, LOW);
    buzzerState = BUZZER_OFF;
  } else {
    digitalWrite(BUZZER_PIN, HIGH);
    buzzerState = BUZZER_ON;
  }
}
References BUZZER_IDLE, BUZZER_OFF, BUZZER_ON, BUZZER_PIN, buzzerState, currentPattern, lastChange, and stepIndex.
Referenced by loop().
Variable Documentation
accessGranted
AccessResult accessGranted
Result of keypad PIN verification.
Definition at line 108 of file esp3.ino.
adminServoControl
bool adminServoControl = false
Enables direct servo control via potentiometer (admin mode).
Definition at line 123 of file esp3.ino.
Referenced by callback(), and loop().
beepTimings
const unsigned int beepTimings[]
Initial value:
                               = {
  125
}
Keypad tap sound: short beep.
Definition at line 154 of file esp3.ino.
                                 {
  125
};
Referenced by playTapSound().
BUZZER_PIN
uint8_t BUZZER_PIN = 14 [constexpr]
Piezo buzzer.
Definition at line 76 of file esp3.ino.
Referenced by playPattern(), setup(), stopBuzzer(), and updateBuzzer().
buzzerState
BuzzerState buzzerState = BUZZER_IDLE
Current buzzer state.
Definition at line 176 of file esp3.ino.
Referenced by playPattern(), stopBuzzer(), and updateBuzzer().
currentPattern
BuzzerPattern currentPattern = {nullptr, 0}
Currently active buzzer pattern.
Definition at line 179 of file esp3.ino.
{nullptr, 0};
Referenced by playPattern(), and updateBuzzer().
deniedTimings
const unsigned int deniedTimings[]
Initial value:
                                 = {
  2000
}
Denied access: single long beep.
Extra long to scare
Definition at line 136 of file esp3.ino.
                                   {
  2000
};
Referenced by playDeniedSound().
DEVICE_ID
char DEVICE_ID[] = "door1" [constexpr]
Unique device identifier used in MQTT topics.
Definition at line 63 of file esp3.ino.
GREEN_PIN
uint8_t GREEN_PIN = 0 [constexpr]
Green LED (unlocked).
Definition at line 75 of file esp3.ino.
Referenced by callback(), forceLock(), and setup().
lastChange
unsigned long lastChange = 0
Timestamp of last buzzer state change.
Definition at line 185 of file esp3.ino.
Referenced by playPattern(), and updateBuzzer().
lock_servo
Servo lock_servo
Servo instance controlling the lock mechanism.
Definition at line 114 of file esp3.ino.
Referenced by callback(), forceLock(), loop(), and setup().
lockTimings
const unsigned int lockTimings[]
Initial value:
                               = {
  250, 120,
  250, 120,
  250
}
Lock sound: long-long-long pattern.
Definition at line 141 of file esp3.ino.
                                 {
  250, 120,
  250, 120,
  250
};
Referenced by playLockSound().
MQTT_HOST
char MQTT_HOST[] = "maqiatto.com" [constexpr]
MQTT broker hostname.
Definition at line 54 of file esp3.ino.
MQTT_PASS
char MQTT_PASS[] = "potter" [constexpr]
MQTT password.
Definition at line 60 of file esp3.ino.
MQTT_PORT
uint16_t MQTT_PORT = 1883 [constexpr]
MQTT broker port.
Definition at line 56 of file esp3.ino.
MQTT_USER
char MQTT_USER[] = "hectorfoss@gmail.com" [constexpr]
MQTT username.
Definition at line 58 of file esp3.ino.
net
WifiMqttClient net
WiFi + MQTT client wrapper.
Definition at line 46 of file esp3.ino.
RED_PIN
uint8_t RED_PIN = 4 [constexpr]
GPIO pin assignments.
Refer to esp3.fzz for wiring details. Red LED (locked / denied)
Definition at line 74 of file esp3.ino.
Referenced by callback(), forceLock(), and setup().
rfidAccess
bool rfidAccess = false
Indicates whether RFID access was granted.
Definition at line 111 of file esp3.ino.
SERVO_PIN
uint8_t SERVO_PIN = 13 [constexpr]
Servo signal pin.
Definition at line 77 of file esp3.ino.
Referenced by setup().
servoAngle
uint8_t servoAngle
Current servo angle (derived from potentiometer in admin mode).
Definition at line 120 of file esp3.ino.
Referenced by loop(), and setup().
servoOpen
bool servoOpen = false
Indicates whether the servo is currently in the open position.
Definition at line 117 of file esp3.ino.
Referenced by callback(), and forceLock().
stepIndex
uint8_t stepIndex = 0
Index into the timing array.
Definition at line 182 of file esp3.ino.
Referenced by playPattern(), and updateBuzzer().
UNLOCK_TIME_MS
uint32_t UNLOCK_TIME_MS = 5000 [constexpr]
Door unlock duration (ms).
Definition at line 87 of file esp3.ino.
unlocked
bool unlocked = false
Indicates whether the door is currently unlocked.
Definition at line 97 of file esp3.ino.
Referenced by callback(), forceLock(), and loop().
unlockTimings
const unsigned int unlockTimings[]
Initial value:
                                 = {
  125, 120,
  125
}
Unlock sound: short-short pattern.
Definition at line 148 of file esp3.ino.
                                   {
  125, 120,
  125
};
Referenced by playUnlockSound().
unlockUntil
uint32_t unlockUntil = 0
Timestamp (ms) until which the door remains unlocked.
Definition at line 90 of file esp3.ino.
Referenced by callback(), and loop().
WIFI_PASS
char WIFI_PASS[] = "mrbombasticcallmefantastic" [constexpr]
WiFi password.
Definition at line 51 of file esp3.ino.
WIFI_SSID
char WIFI_SSID[] = "Mathias2.4" [constexpr]
WiFi SSID.
Definition at line 49 of file esp3.ino.